version: '3.8'
services:
  db:
    extends:
      file: ../database/docker-compose.yml
      service: db

  redis:
    extends:
      file: ../database/docker-compose.yml
      service: redis

  cms:
    image: registry-hub.smatflow.net/smatflow-projects/smatflow-portal/cms:latest
    depends_on:
      - db
      - redis
    restart: unless-stopped
    env_file:
      - ../../apps/cms/.env.sample
      - .env
    ports:
      - 8055:8055
    volumes:
      - cms-database:/app/apps/cms/database
      - cms-extensions:/app/apps/cms/extensions
      - cms-uploads:/app/apps/cms/uploads

volumes:
  db-data:
  redis-data:
  cms-database:
  cms-extensions:
  cms-uploads:
