default:
  tags:
    - smatflow-projects-runner

stages:
  - front-test
  - deploy-testing
  - deploy-staging
  - deploy-production

  - build-images

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

############## Front assets build test #####################

front-test:
  image: node:16.16
  stage: front-test
  cache:
    key: node_modules-cache
    paths:
      - node_modules/
  only:
    refs:
      - main
      - tags
  script:
    # Install PNPM and project Node dependencies.
    - npm install pnpm --location=global
    - pnpm --version

    - pnpm install
    # run test or build
    - pnpm run build

# ############# Servers deployments #########################

# ######## testing (Coding) #####
deploy-testing:
  stage: deploy-testing
  image: python:3.10
  needs: [front-test]
  only:
    refs:
      - main
      - tags
    variables:
      - $ANSIBLE_VAULT_PASS
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  environment:
    name: testing-env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - echo "$AUTH_LDAP_DEFAULT_ROLE_ID__TESTING"
    - echo "$DOCS_GENERATOR_ENV__TESTING"

    - make provision-cd limits=testing
  when: manual

# ######## Staging ##############################

deploy-staging:
  stage: deploy-staging
  image: python:3.10
  needs: [deploy-testing]
  only:
    refs:
      - main
      - tags
    variables:
      - $CI_COMMIT_TAG
      - $ANSIBLE_VAULT_PASS
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  environment:
    name: staging-env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - echo "$AUTH_LDAP_DEFAULT_ROLE_ID__CODING"
    - echo "$DOCS_GENERATOR_ENV__CODING"

    - make provision-cd limits=coding

# ######## Production ##############################

deploy-production:
  stage: deploy-production
  image: python:3.10
  needs: [deploy-testing]
  only:
    refs:
      - main
      - tags
    variables:
      - $CI_COMMIT_TAG
      - $ANSIBLE_VAULT_PASS
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  environment:
    name: staging-env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - echo "$AUTH_LDAP_DEFAULT_ROLE_ID__PRODUCTION"
    - echo "$DOCS_GENERATOR_ENV__PRODUCTION"

    - make provision-cd limits=production
  when: manual

# ############# Build docker images #########################

build-images:
  image: docker:23.0.5
  stage: build-images
  needs: [front-test]
  services:
    - docker:23.0.5-dind
  only:
    refs:
      - main
      - tags
    variables:
      - $CI_COMMIT_TAG
  before_script:
    - echo "user:$CI_REGISTRY_USER -- pwd:$CI_REGISTRY_PASSWORD -- registry:$CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "$CI_COMMIT_TAG"
    - echo "$CI_COMMIT_TAG_MESSAGE"
  script:
    - echo "Build Images, and create release"
    # - make docker-publish
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE"
  when: manual
