default:
  tags:
    - smatflow-projects-runner

stages:
  - front-test
  - deploy-site-smatflow-org
  - deploy-www-smatflow-org
  - deploy-3d-smatflow-org
  - deploy-www-civicflow-org
  - deploy-www-smatflow-academy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

############## Front assets build test #####################

front-test:
  image: node:18
  stage: front-test
  cache:
    key: node_modules-cache
    paths:
      - node_modules/
  rules:
    - if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Merge branch.*/)
    - if: $CI_COMMIT_BRANCH == "etiolles"
    - if: $CI_PIPELINE_SOURCE == "web"

  script:
    - npm install pnpm@9.1.4 --location=global
    - pnpm --version
    - pnpm install
    - pnpm run build

# ############# Servers deployments #########################

.deploy:
  image: python:3.10
  needs: [front-test]
  rules:
    - if: $CI_COMMIT_TAG || ($CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^Merge branch.*/)
    - if: $CI_COMMIT_BRANCH == "etiolles"
    - if: $CI_PIPELINE_SOURCE == "web"

  cache:
    key: pip-cache
    paths:
      - .cache/pip

  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")

  script:
    - export CMS_LDAP_ENABLED_VAR=$([ "$CMS_LDAP_ENABLED" = "true" ] && echo "true" || echo "false")
    - export EXTRA_VARS="repository_url=$CI_REPOSITORY_URL domain_var=$SITE_DOMAIN cms_domain_var=$CMS_DOMAIN cms_ldap_auth_var=$CMS_LDAP_ENABLED_VAR"
    - ansible-playbook --vault-password-file .vault_pass ansible/install.yml -u "$ANSIBLE_SERVER_USER" -i "$ANSIBLE_SERVER_HOST," --extra-vars "$EXTRA_VARS"

deploy-site-smatflow-org:
  extends: .deploy
  stage: deploy-site-smatflow-org
  environment:
    name: site-smatflow-org
  when: manual

deploy-www-smatflow-org:
  extends: .deploy
  stage: deploy-www-smatflow-org
  environment:
    name: www-smatflow-org
  when: manual

deploy-3d-smatflow-org:
  extends: .deploy
  stage: deploy-3d-smatflow-org
  environment:
    name: 3d-smatflow-org
  when: manual

deploy-www-civicflow-org:
  extends: .deploy
  stage: deploy-www-civicflow-org
  environment:
    name: www-civicflow-org
  when: manual

deploy-www-smatflow-academy:
  extends: .deploy
  stage: deploy-www-smatflow-academy
  environment:
    name: www-smatflow-academy
  when: manual
