default:
  tags:
    - icloudeng-system-v15

cache:
  paths:
    - node_modules/
    - apps/web/node_modules/
    - apps/cms/node_modules/

stages:
  - front-test
  - deploy-job

# before_script:
# - composer install

front-test:
  image: node:16.16
  stage: front-test
  only:
    refs:
      - main
  script:
    # Install PNPM and project Node dependencies.
    - npm install pnpm --location=global
    - pnpm install
    # run test or build
    - pnpm -r build

deploy-job:
  stage: deploy-job
  image: python:3.8
  only:
    refs:
      - main
  environment:
    name: coding env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - make provision-cd limits=coding
  when: manual
