default:
  tags:
    - smatflow-projects-runner

stages:
  - front-test
  - deploy-coding
  - deploy-testing

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

front-test:
  image: node:16.16
  stage: front-test
  cache:
    key: node_modules-cache
    paths:
      - node_modules/
  only:
    refs:
      - main
  script:
    # Install PNPM and project Node dependencies.
    - npm install pnpm --location=global
    - pnpm install
    # run test or build
    - pnpm run build

deploy-coding:
  stage: deploy-coding
  image: python:3.10
  only:
    refs:
      - main
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  environment:
    name: coding env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - echo "$AUTH_LDAP_DEFAULT_ROLE_ID__CODING"
    - make provision-cd limits=coding
  when: manual
#
deploy-testing:
  stage: deploy-testing
  image: python:3.10
  needs: [deploy-coding]
  only:
    refs:
      - main
  cache:
    key: pip-cache
    paths:
      - .cache/pip
  environment:
    name: testing env
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - bash cicd_vars.sh
    - make ansible-install-cd
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ANSIBLE_DEPLOY_KEY")
  script:
    - echo "$AUTH_LDAP_DEFAULT_ROLE_ID__TESTING"
    - make provision-cd limits=testing
