version: '3.8'
services:
  db:
    image: postgis/postgis:12-3.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: icloudeng_portal
    networks:
      - icloudeng_portal
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  icloudeng_portal: {}

volumes:
  db-data:
