services:
  db:
    extends:
      file: docker/database/docker-compose.yml
      service: db

  redis:
    extends:
      file: docker/database/docker-compose.yml
      service: redis

  typesense:
    extends:
      file: docker/database/docker-compose.yml
      service: typesense

  cms:
    depends_on:
      - db
      - redis
    extends:
      file: docker/cms/docker-compose.yml
      service: cms

  docsearch-scraper:
    depends_on:
      - typesense
      - redis
    extends:
      file: docker/docsearch-scraper/docker-compose.yml
      service: docsearch-scraper

  docs:
    depends_on:
      - typesense
      - redis
      - cms
    extends:
      file: docker/docs/docker-compose.yml
      service: docs

  web:
    depends_on:
      - cms
    extends:
      file: docker/web/docker-compose.yml
      service: web

volumes:
  db-data:
  redis-data:
  typesense-data:

  cms-database:
  cms-extensions:
  cms-uploads:

  web-cache:

  docs-i18n:
  docs-data:
  docs-meta:
  docs-build:
  docs-scraper-meta:
  docs-docusaurus:
