apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
spec:
  selector:
    matchLabels:
      app: typesense
  replicas: 3
  serviceName: "typesense"
  minReadySeconds: 10
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: typesense
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: typesense
          image: typesense/typesense:0.25.0
          ports:
            - containerPort: 8108
              name: typesense
          volumeMounts:
            - name: typesense-data
              mountPath: /data
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          command:
            - --data-dir
            - /data
            - --api-key=xyz
            - --enable-cors
      volumes:
        - name: typesense-data
          persistentVolumeClaim:
            claimName: typesense-pvc
