apiVersion: v1
kind: Service
metadata:
  name: typesense
  labels:
    app: typesense
spec:
  ports:
    - port: 8108
      name: typesense
  clusterIP: None
  type: LoadBalancer
  selector:
    app: typesense
