version: '3.8'
services:
  db:
    extends:
      file: ../cms/docker-compose.yml
      service: db

  redis:
    extends:
      file: ../cms/docker-compose.yml
      service: redis

  cms:
    extends:
      file: ../cms/docker-compose.yml
      service: cms

  web:
    image: registry-hub.smatflow.net/smatflow-projects/smatflow-portal/web:latest
    depends_on:
      - cms
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  db-data:
  redis-data:
  cms-database:
  cms-extensions:
  cms-uploads:
