---
# handlers file for tools/ansible/roles/nginx
- name: nginx reload
  service:
    name: nginx
    state: reloaded

- name: nginx restart
  service:
    name: nginx
    state: restarted

- name: fail2ban restart
  service:
    name: fail2ban
    state: restarted
