version: '3.8'
services:
  docsearch-scraper:
    image: registry-hub.smatflow.net/smatflow-projects/smatflow-portal/docsearch-scraper:latest
    restart: unless-stopped
    env_file:
      - ../../tools/docsearch-scraper/docker.env
    environment:
      - TYPESENSE_HOST=typesense
      - DOCS_WEB_URL=http://docs:3100
    volumes:
      - docs-scraper-meta:/root/meta:ro

volumes:
  docs-scraper-meta:
