services:
  db:
    image: postgis/postgis:12-3.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: portal
      POSTGRES_DB: portal
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.8-alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis-data:/data

  typesense:
    image: typesense/typesense:0.23.1
    restart: unless-stopped
    env_file:
      - ../../tools/typesense/docker.env
    ports:
      - 127.0.0.1:8108:8108
    volumes:
      - typesense-data:/data

volumes:
  db-data:
  redis-data:
  typesense-data:
