apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cnpg
spec:
  description: "Cluster database smatflow"
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgis:14

  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  postgresql:
    parameters:
      shared_buffers: 256MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      auto_explain.log_min_duration: "10s"
    pg_hba:
      - host all all 10.244.0.0/16 md5
      - host all all 10.233.0.0/16 md5
      - host all all 10.178.0.0/16 md5
      - host all all 192.168.44.0/24 md5

  superuserSecret:
    name: cnpg-cluster-superuser

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: cnpg-cluster-app-user
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;

  storage:
    storageClass: longhorn
    size: 5Gi

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: failure-domain.beta.kubernetes.io/zone

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false
