- name: DOCSEARCH-SCRAPER (Typesense) | docker.env config
  set_fact:
    env_docker_file: "{{ root_path }}/tools/typesense/docker.env"

- name: DOCSEARCH-SCRAPER (Typesense) | docker.env config (TYPESENSE_CORS_DOMAINS)
  lineinfile:
    path: "{{ env_docker_file }}"
    regexp: "^TYPESENSE_CORS_DOMAINS="
    line: "TYPESENSE_CORS_DOMAINS=https://{{ domain }}"

- name: DOCSEARCH-SCRAPER(Docker Compose) | Mount and Run typesense
  command: docker compose up typesense -d
  args:
    chdir: "{{ root_path }}"

- name: DOCSEARCH-SCRAPER | Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5

- name: DOCSEARCH-SCRAPER | docsearch-scraper docs
  become: false
  command: "make docsearch-scraper"
  args:
    chdir: "{{ root_path }}"

- name: "DOCSEARCH-SCRAPER | Cron docsearch-scraper docs"
  cron:
    name: "docusaurus-docsearch-scraper"
    special_time: hourly
    job: "cd {{ root_path }} && make docsearch-scraper"
