- name: Docs Config
  debug:
    msg: Hello Docs Config

- name: Docs App | .env config
  set_fact:
    env_docs_file: "{{ root_path }}/apps/docs/.env"

- name: Docs App .env config | TYPESENSE_HOST
  lineinfile:
    path: "{{ env_docs_file }}"
    regexp: "^TYPESENSE_HOST="
    line: "TYPESENSE_HOST={{ domain }}"

- name: Docs App .env config | TYPESENSE_PORT
  lineinfile:
    path: "{{ env_docs_file }}"
    regexp: "^TYPESENSE_PORT="
    line: "TYPESENSE_PORT={{ typesense_gateway_port }}"

- name: Docs App .env config | TYPESENSE_PROTOCOL
  lineinfile:
    path: "{{ env_docs_file }}"
    regexp: "^TYPESENSE_PROTOCOL="
    line: "TYPESENSE_PROTOCOL=https"
  when: typesense_gateway_port != 80

- name: Docs App .env config | TYPESENSE_PROTOCOL
  lineinfile:
    path: "{{ env_docs_file }}"
    regexp: "^TYPESENSE_PROTOCOL="
    line: "TYPESENSE_PROTOCOL=http"
  when: typesense_gateway_port == 80
