---
# tasks file for ansible/roles/app
- name: App Repository | Clone
  become: false
  git:
    repo: "{{ app_git_repo }}"
    dest: "{{ root_path }}"
    force: yes
    version: "{{ app_git_version }}"

- name: PNPM | Setup
  become: false
  command: pnpm setup
  args:
    chdir: "{{ root_path }}"
  ignore_errors: true

- name: App Client | Download client dependencies
  become: false
  command: pnpm install
  args:
    chdir: "{{ root_path }}"

- include_tasks: cms-config.yml
- include_tasks: web-config.yml

- name: PM2 | unstartup Script
  command: "pm2 unstartup systemd"
  ignore_errors: true

# CMS App
#
- name: CMS App | App bootstrap
  become: false
  command: pnpm run bootstrap
  args:
    chdir: "{{ root_path }}/apps/cms"

- name: CMS App | App apply snapshot
  become: false
  command: pnpm run apply
  args:
    chdir: "{{ root_path }}/apps/cms"
    removes: "{{ root_path }}/apps/cms/snapshot.yaml"

- name: CMS App | Directus Extensions Build
  become: false
  command: pnpm -r extension-build
  ignore_errors: true
  args:
    chdir: "{{ root_path }}/apps/cms"

- name: CMS App | Create App User
  become: false
  command: "node create-app-user.js"
  args:
    chdir: "{{ root_path }}/apps/cms"

- name: CMS App | Delete old pm2 process
  command: "pm2 delete {{ admin_domain }}"
  args:
    chdir: "{{ root_path }}/apps/cms"
  ignore_errors: true

- name: CMS App | Start the server
  command: "pm2 start npm --name {{ admin_domain }} -- run start"
  args:
    chdir: "{{ root_path }}/apps/cms"

# Web App
#
- name: "Web App | .env.local"
  template:
    src: .env.local-web
    dest: "{{ root_path }}/apps/web/.env.local"
    force: yes

- name: Web App | Build client assets
  become: false
  command: pnpm build
  args:
    chdir: "{{ root_path }}/apps/web"

- name: Web App | Delete old pm2 process
  command: "pm2 delete {{ domain }}"
  args:
    chdir: "{{ root_path }}/apps/web"
  ignore_errors: true

- name: Web App | Start the server
  command: "pm2 start npm --name {{ domain }} -- run start"
  args:
    chdir: "{{ root_path }}/apps/web"

- name: PM2 | Generating a Startup Script
  command: "pm2 startup"

- name: PM2 | Save the app list to be restored at reboot
  command: "pm2 save"

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  ignore_errors: true
