---
# tasks file for tools/ansible/roles/node

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs {{ node_version }} LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install the nodejs {{ node_version }} LTS
  apt:
    update_cache: yes
    name:
      - nodejs
      - yarn
    state: latest

- name: NPM | Install PNPM
  npm:
    name: pnpm
    global: yes
    state: latest

- name: NPM | Install PM2
  npm:
    name: pm2
    global: yes
    state: present
