apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: cms-uploads
  name: cms-uploads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
