apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: docs-build
  name: docs-build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
