apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: docs-i18n
  name: docs-i18n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
