apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: docs-meta
  name: docs-meta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
