---
- name: LetsEncrypt | Check if certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_item }}/fullchain.pem"
  register: certificate

- name: LetsEncrypt | Remove cert configuration from vhost
  when: not certificate.stat.exists
  shell:
    cmd: |
      sed -i -r 's/(listen .*443)/\1;#/g; s/(ssl_(certificate|certificate_key|trusted_certificate) )/#;#\1/g' /etc/nginx/sites-available/{{ domain }}
    creates: "/etc/letsencrypt/live/{{ domain_item }}/fullchain.pem"
  ignore_errors: true

- name: LetsEncrypt | Reload nginx
  when: not certificate.stat.exists
  service:
    name: nginx
    state: reloaded

- name: LetsEncrypt | Certbot (--dry-run) {{ domain_item }} certificate
  shell:
    cmd: "certbot certonly --webroot -d {{ domain_item }} --email contact@{{ company_domain }} -w /var/www/_letsencrypt -n --agree-tos --dry-run"
    creates: "/etc/letsencrypt/live/{{ domain_item }}/fullchain.pem"

- name: LetsEncrypt | Certbot {{ domain_item }} certificate
  shell:
    cmd: "certbot certonly --webroot -d {{ domain_item }} --email contact@{{ company_domain }} -w /var/www/_letsencrypt -n --agree-tos"
    creates: "/etc/letsencrypt/live/{{ domain_item }}/fullchain.pem"
