apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smatflow-portal

resources:
  - "dockerconfig.yaml"
  - "namespace.yaml"
  - "postgres"
  - "redis"
  - "typesense"
  - "web"
  - "cms"
  - "docs"
  - "docsearch-scraper"
  - "ingress.yaml"
#
# Use Kubeseal to encrypt dockerconfigjson
# secretGenerator:
#   - name: regcred
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - .dockerconfigjson
