apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smatflow-portal

resources:
  - "namespace.yaml"
  - "postgres"
  - "redis"
  - "typesense"
  - "web"
  - "cms"
  - "docs"
  - "docsearch-scraper"

secretGenerator:
  - name: regcred
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson
