apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app
  namespace: smatflow-portal
  # labels:
  #   app: web-app
data:
  .env: |
    NEXT_PUBLIC_COMPANY_NAME="Smatflow LTD"
    NEXT_PUBLIC_WEBSITE_URL=https://www.smatflow.xyz

    CMS_URL=https://portaladmin.smatflow.xyz
    DIRECTUS_URL=https://portaladmin.smatflow.xyz
    DIRECTUS_STATIC_TOKEN=mdzjETutYM06z9ch56CmFkjIOWZCwraG

---
kind: Service
apiVersion: v1
metadata:
  name: web-app
  namespace: smatflow-portal
spec:
  selector:
    app: web-app
  ports:
    - name: web-app
      port: 80
      targetPort: 3000
  type: LoadBalancer
  # externalTrafficPolicy: Local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: smatflow-portal
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: registry-hub.smatflow.net/smatflow-projects/smatflow-portal/web
          name: web-app
          resources:
            limits:
              cpu: "200m"
              memory: "550M"
          ports:
            - containerPort: 3000
              name: web-app

          volumeMounts:
            - name: config
              mountPath: "/app/apps/web"
              readOnly: true

      restartPolicy: Always

      imagePullSecrets:
        - name: regcred

      volumes:
        - name: config
          configMap:
            name: web-app
            items:
              - key: ".env"
                path: ".env"
