---
# tasks file for ansible/roles/docker
- name: Docker | Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Docker | Install required system packages
  apt:
    name:
      - uidmap
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Docker | Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker | Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Docker | Install
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
    state: present
    update_cache: true

- name: Docker | Install Docker Module for Python
  pip:
    name: docker

- name: Docker | Add group user
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
