---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/
- name: Install all applications prerequisites
  hosts: remote
  become: yes

  pre_tasks:
    - name: "APT | Update & Upgrade"
      become: yes
      apt:
        upgrade: dist
        update_cache: yes

  environment:
    APP_ENV: "{{ app_env }}"
    APP_DEBUG: "{{ app_debug }}"

  tasks:
    - name: App CMS .env config
      set_fact:
        auth_ldap_role_id: "AUTH_LDAP_DEFAULT_ROLE_ID_{{ inventory_hostname | upper }}"
      tags: debug
    - debug:
        msg: "fdsafds {{ lookup('env', auth_ldap_role_id) }} ---- {{ auth_ldap_role_id }}"
      tags: debug

  roles:
    - { role: tools, tags: tools }
    - { role: docker, tags: docker, when: docker_install }
    - { role: firewall, tags: firewall }
    - { role: nginx, tags: nginx }
    - { role: pgsql, tags: pgsql, when: not docker_install }
    - { role: node, tags: node }
    - { role: app, tags: app }
