apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docsearch-scraper-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "100Mi"
