apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smatflow-portal

resources:
  - "service.yaml"
  - "docsearch-scraper-volume.yaml"
  - "volume.yaml"
  - "deployment.yaml"

configMapGenerator:
  - name: docs-app-config
    envs:
      - ".env.config"

secretGenerator:
  - name: docs-app-secrets
    envs:
      - ".env.secrets"
